// --- DATA FROM THE BOOK "Improwizacja wg Johnstone'a" ---

export const lifeGameQuestions = [
    "Jakim superbohaterem chciałeś/chciałaś być w dzieciństwie?",
    "Które z obelg po swoim adresem pamiętasz do dzisiaj?",
    "Jak wyglądał twój młodzieńczy bunt?",
    "Kto złamał ci serce?",
    "Jakie było najgorsze zajęcie, jakim się kiedykolwiek zajmowałeś/zajmowałaś?",
    "Czy kiedykolwiek oszukiwałeś/oszukiwałaś z zimną krwią?",
    "Czy byłeś/byłaś kiedyś tak pijany/pijana, że nie pamiętasz, jak skończył się wieczór?",
    "Czemu rzuciłeś/rzuciłaś dziewczynę/chłopaka, z którym chodziłeś/chodziłaś tak długo?",
    "Jakie były najlepsze lata twojego życia?",
    "Czy masz jakieś powracające sny?",
    "Opisz swoją sypialnię z dzieciństwa.",
    "Jaka jest twoja największa tajemnica?",
    "Czego najbardziej żałujesz?"
];

export const behaviors = {
    high_status: [
        "Zmiażdż każde wyzwanie.",
        "Utrzymuj kontakt wzrokowy min. 5 sekund.",
        "Trzymaj głowę nieruchomo, gdy mówisz.",
        "Mrugaj rzadziej niż twój partner.",
        "Poruszaj się płynnie, często zastygaj w bezruchu.",
        "Używaj długiego 'yyy' zanim rozpoczniesz zdanie.",
        "Zajmuj dużo miejsca (rozszerz stopy).",
        "Dotykaj twarzy innych, klep ich po głowie.",
        "Mów pełnymi zdaniami.",
        "Weź kilka oddechów zanim coś powiesz."
    ],
    low_status: [
        "Podziwiaj rzeczy innych, ale skrycie.",
        "Odpowiadaj natychmiast.",
        "Przygryzaj dolną wargę podczas uśmiechu.",
        "Miej szeroko otwarte oczy.",
        "Trać oddech gdy mówisz.",
        "Przerywaj kontakt wzrokowy, ale sprawdzaj czy partner patrzy.",
        "Uwłaczaj sobie ochoczo.",
        "Śmiej się na krótkim oddechu (nerwowy chichot).",
        "Drap się nerwowo po kolanach.",
        "Często dotykaj swojej twarzy (zakrywaj usta).",
        "Łącz stopy palcami (pięty na zewnątrz).",
        "Trzymaj łokcie blisko tułowia."
    ],
    annoying: [
        "Mów innym, że cię nudzą.",
        "Przedrzeźniaj sposób zachowania osoby.",
        "Bądź nadmiernie uprzejmy (sarkastycznie).",
        "Pożycz coś i zepsuj/zgub.",
        "Próbuj kontrolować tę osobę.",
        "Krytykuj: wygląd, zwierzęta, język.",
        "Udzielaj niechcianych rad.",
        "Jęcz, warcz, zgrzytaj zębami.",
        "Naruszaj osobistą przestrzeń (stań za blisko).",
        "Przerywaj, gdy ktoś mówi.",
        "Źle rozum osobę (przesłyszenia).",
        "Zaczynaj zdania od 'ty zawsze' albo 'ty nigdy'.",
        "Mów tylko o sobie."
    ],
    charming: [
        "Zadawaj pytania o drugą osobę.",
        "Pytaj o radę lub opinię.",
        "Komplementuj (głos, ciało, ubiór).",
        "Zauważaj ludzi pierwszy (wituj entuzjastycznie).",
        "Znajduj innym partnerów/przyjaciół.",
        "Pozwalaj innym mówić o sobie.",
        "Dawaj drobne prezenty.",
        "Pozwól im wygrać.",
        "Proponuj jedzenie, picie, seks, pieniądze.",
        "Cytuj partnera z podziwem.",
        "Podziel się jakimś sekretem.",
        "Opowiadaj miłe historie o rozmówcy."
    ],
    seduce_m: [
        "Poproś go do tańca.",
        "Podziwiaj jego gust.",
        "Trać oddech przy nim.",
        "Siadaj blisko (podwijając nogi).",
        "Bądź dwuznaczna.",
        "Bądź podatna na zranienie.",
        "Pieść/głaszcz siebie.",
        "Śmiej się z jego żartów.",
        "Spraw, by czuł się wyjątkowy.",
        "Powtarzaj w myśli: 'Weź mnie!'.",
        "Jedz uwodzicielsko.",
        "Zwilżaj wargi.",
        "Dotykaj go, gdy mówisz."
    ],
    seduce_w: [
        "Bądź chłopięcy, figlarny.",
        "Bądź blisko niej.",
        "Martw się, że możesz być gejem.",
        "Bądź 'samotny'.",
        "Mów otwarcie o osobistych sprawach.",
        "Błagaj, płacz, płaszcz się.",
        "Komplementuj.",
        "Posiadaj wadę (ranę, impotencję).",
        "Powtarzaj w myśli: 'Kocham cię'.",
        "Utrzymuj kontakt wzrokowy.",
        "Rzuć się na nią, a potem przepraszaj.",
        "Kochaj małe zwierzątka i dzieci.",
        "Dotknij jej piersi 'przez przypadek'."
    ],
    hero: [
        "Posiadaj broń.",
        "Bądź czujny, wykrywaj zagrożenia.",
        "Miej wroga.",
        "Objawiaj siłę i muskulaturę.",
        "Miej mocny, rezonujący głos.",
        "Śmiej się dużo (pokazuj zęby).",
        "Zabij coś/kogoś.",
        "Uratuj kogoś.",
        "Opowiadaj o niezwykłych przygodach.",
        "Pokaż blizny.",
        "Wyobraź sobie świetlistą kulę w piersi.",
        "Bądź nieczuły na ból.",
        "Spraw, by ludzie czuli się bezpieczni przy tobie."
    ],
    beautiful: [
        "Bądź powolna, omdlewająca.",
        "Kontroluj wygląd (szukaj lustra).",
        "Tańcz/pozuj.",
        "Dużo się śmiej (pokazuj zęby).",
        "Dotykaj i głaszcz się.",
        "Chodź wyprostowana.",
        "Martw się o figurę/skórę.",
        "Pytaj o własną atrakcyjność.",
        "Czyhaj na komplementy.",
        "Nudź się, gdy rozmowa nie dotyczy ciebie.",
        "Miej lepszy profil.",
        "Wydawaj sensualne dźwięki.",
        "Panikuj, gdy znajdziesz pryszcz."
    ],
    party: [
        "Podziwiaj ludzi i rzeczy.",
        "Zgadzaj się (akceptuj wszystko).",
        "Bądź głośny/a.",
        "Zachęcaj do łamania reguł.",
        "Znaj fascynujące plotki.",
        "Pamiętaj imiona (używaj ich).",
        "Inicjuj zabawy/tańce.",
        "Łam tabu.",
        "Wygłupiaj się / rób sztuczki.",
        "Przebieraj się w ubrania innych.",
        "Namawiaj do picia/złego zachowania.",
        "Zaproponuj rozbieranego pokera.",
        "Rób 'wielkie wejścia' (ta-dam!)."
    ],
    mysterious: [
        "Bądź skryty i milczący.",
        "Rób aluzje.",
        "Odbieraj dziwne telefony/prezenty.",
        "Zachowuj się jak medium (wiedz co będzie).",
        "Śmiej się z własnych myśli.",
        "Znaj sekrety innych.",
        "Miej broń lub wroga.",
        "Patrz tak, jakbyś wszystko rozumiał.",
        "Rób znaczące pauzy.",
        "Bądź w podróży bez powodu (do NASA, więzienia).",
        "Wchodź w trans / bądź opętany.",
        "Oczekuj ataku.",
        "Miej niewytłumaczalne prośby."
    ],
    boring: [
        "Ziewaj.",
        "Przerywaj / zmieniaj temat.",
        "Narzekaj, że ktoś mówi w kółko to samo.",
        "Wiedz, co ktoś chce powiedzieć.",
        "Ignoruj.",
        "Uderzaj głową w ścianę.",
        "Proś, aby wyszedł.",
        "Zadzwoń do kogoś/czytaj gazetę.",
        "Pytaj: 'co?', 'słucham?', 'przepraszam?'.",
        "Gap się, starając się nie patrzeć.",
        "Potwierdzaj zbyt wcześnie (nie słuchając).",
        "Patrz na zegarek."
    ],
    computer: [
        "Bądź skuteczny (wszystko na miejscu).",
        "Bądź chłodny i zdystansowany.",
        "Nie miej przyjaciół (i bądź z tym ok).",
        "Bądź 'drewniany'.",
        "Bądź nieczuły na emocje i ból.",
        "Unikaj kontaktu fizycznego.",
        "Używaj suchego głosu.",
        "Traktuj innych jak wolnych/ospałych.",
        "Pauzuj przed odpowiedzią.",
        "Proponuj rozwiązania.",
        "Powstrzymuj wewnętrznie przemoc."
    ],
    guilty: [
        "Przepraszaj.",
        "Złam albo zniszcz coś.",
        "Spowiadaj się (np. że zabiłeś zwierzątko).",
        "Unikaj patrzenia w oczy / zwieszaj głowę.",
        "Tłumacz się z powodów.",
        "Wprawiaj w zakłopotanie.",
        "Zapominaj zamknąć lodówkę/szafkę.",
        "Pomagaj bardziej niż trzeba.",
        "Pożycz coś i nie oddaj.",
        "Kłam na temat antykoncepcji.",
        "Wyjawiaj sekrety innych.",
        "Wzdychaj."
    ],
    smart: [
        "Poprawiaj ludzi.",
        "Wiedz wszystko.",
        "Wyjaśniaj zaskakujące rzeczy.",
        "Używaj rzadkich słów.",
        "Zachowuj się, jakby inni byli głupsi.",
        "Cytuj statystyki (zmyślaj je).",
        "Wtrącaj obce zdania.",
        "Wydawaj 'myślące' dźwięki (mmm, aaa).",
        "Gwiżdż Bacha.",
        "Miej ze sobą książkę/kalkulator.",
        "Krytykuj i oceniaj.",
        "Rób notatki.",
        "Zaczynaj zdania od: 'Moim zdaniem...'.",
        "Nie słuchaj."
    ],
    bad_parent: [
        "Oskarżaj o brak czułości.",
        "Proś, by coś zrobili, a potem rób to sam.",
        "Poprawiaj wygląd (dziecka/partnera).",
        "Bądź męczennikiem.",
        "Bądź zdegustowany.",
        "Bądź nadopiekuńczy ('Zgwałcą cię!').",
        "Konfiskuj rzeczy.",
        "Twórz przeszkody.",
        "Jedz pozostawione jedzenie.",
        "Porównuj z innymi.",
        "Poniżaj publicznie.",
        "Tylko ty wiesz, jak coś zrobić.",
        "Mów: 'Ty zawsze...', 'Ty nigdy...'."
    ],
    happy: [
        "Miej zachwycający sekret.",
        "Zwracaj się do innych z humorem.",
        "Dotykaj rzeczy i siebie.",
        "Miej w głowie wesołą piosenkę.",
        "Uśmiechaj się dla przyjemności.",
        "Tańcz, śpiewaj.",
        "Bądź spokojny i żywy.",
        "Miej dużo czasu.",
        "Pobłażaj sobie (czekolada!).",
        "Powtarzaj mantrę: 'Kocham to wszystko'.",
        "Rozmawiaj swobodnie o prywatności.",
        "Psuj rzeczy, ale nie czuj winy.",
        "Używaj otwartej postawy."
    ],
    normal: [
        "Zgadzaj się z ostrożnością.",
        "Zadawaj nudne pytania.",
        "Chodź do kościoła.",
        "Kontroluj wygląd i opinie.",
        "Nie przepadaj za dotykiem.",
        "Nie przeklinaj.",
        "Dyskutuj o nudnych rzeczach (pogoda, TV).",
        "Uważaj innych za dziwnych.",
        "Miej psa.",
        "Miej delikatny uśmiech.",
        "Siedź symetrycznie.",
        "Pokazuj zdjęcia rodzinne.",
        "Mów frazesy/komunały.",
        "Panikuj przez moment, wracaj do spokoju."
    ],
    jerk: [
        "Bądź nietaktowny.",
        "Pierz brudy publicznie.",
        "Przechwalaj się.",
        "Miej pretensje do świata.",
        "Wytykaj cudze wady (jesteś głupi/brzydki).",
        "Dręcz i irytuj.",
        "Sprowadzaj wszystko do seksu/wydalania.",
        "Gub wątek.",
        "Opowiadaj bezsensowne dowcipy.",
        "Śmiej się agresywnie.",
        "Naruszaj przestrzeń.",
        "Nigdy nie bierz 'nie' za odpowiedź.",
        "Obwiniaj innych."
    ],
    sympathy: [
        "Wzdychaj.",
        "Miej waleczny uśmiech (przez łzy).",
        "Bądź niezdarna/niedołężna.",
        "Płacz, szlochaj.",
        "Bądź zakłopotana.",
        "Bądź bezrobotna.",
        "Zrań się (wylej coś na siebie).",
        "Zasłoń twarz i płacz.",
        "Miej upośledzenie.",
        "Miej strasznego szefa/partnera.",
        "Karz się, gdy coś nie wyjdzie.",
        "Opowiadaj łzawe historie.",
        "Bądź zła w łóżku / samotna.",
        "Traktuj siebie jako ofiarę."
    ]
};

export const quotes = [
    "Bądź oczywisty!",
    "Nie staraj się być oryginalny!",
    "Bądź przeciętny!",
    "Zrób to, czego chce twój partner!",
    "Jeśli masz pomysł, zrób to od razu!",
    "Nie blokuj! Mów TAK!",
    "Błąd to prezent - uciesz się z niego!",
    "Spraw, by twój partner wyglądał dobrze!",
    "Nie planuj! Bądź tu i teraz!",
    "Zmień status!",
    "Zrób coś fizycznego!",
    "Bądź nudny!",
    "Zaryzykuj!",
    "Powiedz to, co myślisz naprawdę.",
    "Wprowadź Tilt (zmianę)!",
    "Nie bądź dowcipny.",
    "Bądź w kłopotach!",
    "Utrzymuj kontakt wzrokowy.",
    "Oddychaj!",
    "Pozwól się zmienić.",
    "Nie staraj się robić najlepiej jak potrafisz.",
    "Jeśli planujesz - mniej odkrywasz.",
    "Publiczność jest mądrzejsza od reżysera.",
    "Cisza jest zawsze intrygująca."
];

export const scenarios = [
    "A i B są obcymi ludźmi w poczekalni.",
    "A i B są rodzeństwem sprzątającym strych.",
    "A jest szefem, B przychodzi po podwyżkę.",
    "Pierwsza randka w ciemno.",
    "Dwóch saperów rozbraja bombę.",
    "Spotkanie po latach na pogrzebie.",
    "Klient składa reklamację w sklepie zoologicznym.",
    "A uczy B jazdy samochodem.",
    "Dwoje ludzi utknęło w windzie.",
    "Przesłuchanie na policji."
];

export const tilts = [
    "Właśnie odkrywasz, że partner to Twój dawno zaginiony brat.",
    "W Twojej kieszeni znajduje się pistolet, o którym zapomniałeś.",
    "Dowiadujesz się, że oboje jesteście w programie reality-show.",
    "Nagle tracisz wzrok, ale nie chcesz tego przyznać.",
    "Właśnie przypominasz sobie, że partner Cię kiedyś okradł.",
    "To miejsce jest nawiedzone, a Ty słyszysz głosy.",
    "Masz nad partnerem absolutną kontrolę (np. poprzez pstryknięcie).",
    "Partner właśnie wyznał Ci miłość, ale Ty go nienawidzisz.",
    "Zwalniają cię z pracy przez telefon.",
    "Właśnie wygrałeś milion na loterii.",
    "Autostopowicz to tak naprawdę Śmierć.",
    "Wiem o tobie wszystko.",
    "To było moje ulubione miejsce... kiedy jeszcze żyłam."
];

export const mantras = [
    "Kocham cię, ale nigdy cię nie zdobędę.",
    "Nienawidzę cię, ale cię pożądam.",
    "Jestem od ciebie lepszy.",
    "Boję się ciebie.",
    "Chcę cię zabić, ale muszę być miły.",
    "Jestem najpiękniejszą osobą w tym pokoju.",
    "Ukrywam straszną tajemnicę.",
    "Wszystko mnie bawi.",
    "Gardzę tym miejscem.",
    "Chcę tylko, żebyś mnie przytulił."
];

export const locations = [
  "Poczekalnia u dentysty",
  "Pusta plaża o świcie",
  "Winda utknięta między piętrami",
  "Salon meblowy IKEA nocą",
  "Pokład statku kosmicznego",
  "Kolejka po zasiłek",
  "Górskie schronisko podczas burzy",
  "Zaplecze taniej restauracji",
  "Przedział w pociągu",
  "Biblioteka miejska",
  "Cmentarz w nocy"
];

export const games = [
    {
      id: 1,
      title: "Uczenie Delfina",
      category: "Spontaniczność / Komunikacja",
      players: "Grupa",
      description: "Aktor opuszcza salę, grupa wymyśla proste zadanie. Po powrocie grupa naprowadza go dźwiękami (bip-bip) lub klaskaniem.",
      goal: "Uwaga, otwarcie na partnera, czysty umysł."
    },
    {
      id: 2,
      title: "Tak, zróbmy to! (Group-Yes)",
      category: "Akceptacja",
      players: "Grupa",
      description: "Grupa stoi razem. Jedna osoba rzuca pomysł (np. 'Idziemy przez las!'), wszyscy odpowiadają entuzjastycznie 'Tak, zróbmy to!' i wykonują akcję.",
      goal: "Budowanie wspólnej energii, akceptacja ofert."
    },
    {
      id: 3,
      title: "Bitwa Statusowa (1-3)",
      category: "Status",
      players: "3 osoby",
      description: "Trójka aktorów. Każdy wybiera numer: 1 (najwyższy), 2 (średni), 3 (najniższy). Rozgrywają scenę, zachowując hierarchię.",
      goal: "Zrozumienie dynamiki dominacji i podporządkowania."
    },
    {
      id: 4,
      title: "I co dalej? (What comes next?)",
      category: "Storytelling",
      players: "2 osoby",
      description: "Jedna osoba opowiada historię, druga (pasażer) pyta 'I co dalej?'. Jeśli pasażerowi pomysł się nie podoba, mówi 'Nie' (z uśmiechem).",
      goal: "Rozpoznawanie oczekiwań partnera i publiczności."
    },
    {
      id: 5,
      title: "Fast Food Stanisławski",
      category: "Charakterystyczność",
      players: "Dowolna",
      description: "Aktorzy dostają listy zachowań (z tego narzędzia!) i starają się je uwiarygodnić w prostej sytuacji (np. spotkanie w poczekalni).",
      goal: "Szybkie budowanie postaci przez zewnętrzną formę."
    },
    {
      id: 6,
      title: "Tilt (Wstrząs)",
      category: "Storytelling",
      players: "2 osoby",
      description: "Aktorzy plotkują o niczym, aż następuje punkt zwrotny (Tilt), który zmienia relację (np. 'Zabiłam twojego kota').",
      goal: "Posuwanie akcji naprzód przez zmianę."
    },
    {
        id: 7,
        title: "Kapelusze (Hat Game)",
        category: "Uważność",
        players: "2 osoby",
        description: "Dwie osoby grają scenę. Każda próbuje zdjąć kapelusz partnera, chroniąc własny. Uczy uważności i bycia 'tu i teraz'.",
        goal: "Podzielność uwagi między zadaniem fizycznym a sceną."
    },
    {
        id: 8,
        title: "Słowo po słowie",
        category: "Współpraca",
        players: "2 osoby",
        description: "Dwie osoby budują historię, mówiąc na zmianę tylko jedno słowo. Uczy rezygnacji z kontroli.",
        goal: "Budowanie wspólnego umysłu (Group Mind)."
    },
    {
        id: 9,
        title: "Ślepcy (Blind Running)",
        category: "Zaufanie",
        players: "Grupa / Pary",
        description: "Dwie osoby z zamkniętymi oczami konstruują historię słowo po słowie, odgrywając ją. Grupa asekuruje.",
        goal: "Zaufanie i wyostrzenie zmysłów innych niż wzrok."
    },
    {
        id: 10,
        title: "Micetro",
        category: "Format",
        players: "Grupa (do 20)",
        description: "Seria szybkich scenek. Gracze są oceniani przez publiczność, ci z najniższą punktacją odpadają.",
        goal: "Oswajanie się z oceną i porażką w bezpiecznych warunkach."
    }
];
